### ISSUE TITLE
Bug: Cell content exceeds height of a single Page

### ISSUE THREAD

**Issue by cyrilleulmi** [markuskaufmann/CAS_SA_Transfer#24]
cas_sa_transfer-asciidoctor-1  | asciidoctor: ERROR: the table cell on page 37 has been truncated; Asciidoctor PDF does not support table cell content that exceeds the height of a single page

**Comment by markuskaufmann** [comment]
I guess this bug stems from the fact that some ADR alternatives are exceeding the maximum allowed cell height because they are non-breakable.
One possible fix could be to split the alternatives into several rows:

|   |   |
|---|---|
|   **ID** | ... |
|   **Anliegen (Concern)** | ... |
|   **Kontext** | ... |
|   **Alternative 1** | ... |
|   **Alternative 2** | ... |
|   **Alternative n** | ... |
|   **Entscheidung** | ... |
|   **Begründung** | ... |
|   **Follow-up Entscheidungen** | ... |

@cyrilleulmi What do you think?

**Comment by markuskaufmann** [comment]
Update:
This seems to be a known limitation
https://docs.asciidoctor.org/pdf-converter/latest/features/#limitations
and is based off an underlying issue
https://github.com/prawnpdf/prawn-table/issues/41
which hasn't been resolved yet.

I guess for now we will have to split the alternatives into separate rows, so that they don't exceed the page height.

**Comment by markuskaufmann** [comment]
@cyrilleulmi Please have a quick look at your generated PDF and close the issue if ok.

**Comment by cyrilleulmi** [comment]
The workaround is fine, thanks for the fix!
